controller:
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
  service:
    type: NodePort
    externalIPs:
      - 172.16.34.26
defaultBackend:
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
